[build]
  command="npm run build"
  functions = "dist/server"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"