name: Scrape Bandcamp Albums
run-name: ${{ github.actor }} asked for a bandcamp scrape 🚀
on:
  workflow_dispatch:
    # inputs:
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: boolean
      # albumList:
      #   description: 'AlbumList'
      #   required: true
      #   type: array
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: npm i
        
      - name: make data dir
        run: mkdir data

      - name: scrape
        run: npm run scrape

      - name: sendToDatabase
        run: npm run sendToDatabase
