name: Scrape Bandcamp Albums
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    # inputs:
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: boolean
      # albumList:
      #   description: 'AlbumList'
      #   required: true
      #   type: array
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        run: npm i
      - name: scrape
        run: npm run scrape
